### PR TITLE
Added some additional demos/patches/etc

### PR DESCRIPTION
**Pull request by YLFAndy**
Some demos from different sources than the major packs, patches, etc. 

Additional hashes:

[Diff.txt](https://github.com/MiSTer-devel/N64_ROM_Database/files/12612631/Diff.txt)

### CODE REVIEW

**Comment by YLFAndy** [comment]
No longer valid. Closing and I'll re-create one based on the new changes.

**Comment by wwark** [comment]
Thank you for your time on those PRs
I think it is important to put cic before 6102 or 61xx.

**Comment by YLFAndy** [comment]
Those are just log spew I grab for the comment. The commit had the cic.

**Comment by YLFAndy** [comment]
Let me double check though. Thanks for noticing.

**Comment by YLFAndy** [comment]
THANK you for catching this!
________________________________

**Pull request closed without merging**
